name: Run Spotify Script

on:
  schedule:
    # Agenda o script para rodar diariamente às 21:50 no horário do Brasil (00:50 UTC)
    - cron: "50 0 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Atualizando para a versão 3.12, conforme necessário pelo projeto
        
    - name: Install Poetry
      run: |
        pip install poetry
        export PATH="$HOME/.local/bin:$PATH"
      
    - name: Use Python 3.12.1 with Poetry
      working-directory: ./src
      run: |
        poetry env use 3.12.1
        poetry install --no-root

    - name: Run Spotify Script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      working-directory: ./src/assets
      run: |
        poetry run python musicas_recentes_actions.py
    
    - name: Verify if CSV was created
      working-directory: ./src/assets
      run: |
        if [ -f "musicas_ouvidas.csv" ]; then
          echo "CSV file exists."
        else
          echo "CSV file does not exist."
          exit 1
        fi

    - name: Commit and push changes if CSV exists
      working-directory: ./src/assets
      run: |
        if [ -f "musicas_ouvidas.csv" ]; then
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add musicas_ouvidas.csv
          git commit -m "Update musicas_ouvidas.csv"
          git push
        else
          echo "CSV file not found, skipping commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
