name: Run Spotify Script

on:
  schedule:
    # Agenda o script para rodar diariamente às 21:50 no horário do Brasil (00:50 UTC)
    - cron: "50 0 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Poetry
      run: |
        pip install poetry
        export PATH="$HOME/.local/bin:$PATH"
        
    - name: Install dependencies
      run: |
        poetry install
      
    - name: Run Spotify Script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: |
        poetry run python musicas_recentes.py
    
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add musicas_ouvidas.csv
        git commit -m "Update musicas_ouvidas.csv"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
